#################################################################################################################
#
#  This role creates L2TP over IPSec VPN server using openswan and xl2tpd. Remote clients connecting to the VPN
#  server are given a private IP address from the same network where the VPN server is. Traffic is tunneled at
#  Layer 2 level and thus no additional routing is needed to reach other hosts in the same private network. By default
#  the VPN server listens the interface through which the server host communicates to its default gateway (= normally
#  the internet facing interface).
#
#  Add role and set VPN password & pre-shared key:
#
#    - role: l2tp_vpn_server
#      l2tp_vpn_psk: "my-password"
#
#  'l2tp_vpn_psk' is used both as VPN authentication password and IPSec tunnel's pre-shared key.
#  Username for VPN authentication is not checked.
#
#  In order for the VPN connection to be established the following ports must be open to internet (and have
#  working port forwarding if VPN host is behind NAT):
#
#    - 500 UDP
#    - 4500 UDP
#    - 1701 UDP
#
---
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - strongswan
    - xl2tpd
  register: task_result
  until: task_result is success
  retries: 2
  delay: 5

- name: Enable IPv4 forwarding
  lineinfile: dest=/etc/sysctl.conf regexp='.*net.ipv4.ip_forward.*' line='net.ipv4.ip_forward=1'
  notify: reload_sysctl

- name: Configure IPSec
  template: src=ipsec.conf.j2 dest=/etc/ipsec.conf
  notify: restart_ipsec

- name: Add dhcpcd hook that restarts ipsec when inet interface comes up
  copy: src=80-ipsec.dhcpcd.conf dest=/lib/dhcpcd/dhcpcd-hooks/80-ipsec.conf

- name: Set IPSec PSK secret
  lineinfile:
    dest: /etc/ipsec.secrets
    regexp: "^%any %any : PSK.*"
    line: "%any %any : PSK \"{{ l2tp_vpn_psk }}\""
    create: yes
  notify: restart_ipsec

- name: Enable ipsec secrets
  lineinfile:
    dest: /etc/strongswan.d/charon/stroke.conf
    regexp: "^    secrets_file = .*"
    line: "    secrets_file = /etc/ipsec.secrets"
    insertafter: "^    # secrets_file = .*"
  notify: restart_ipsec

- name: Configure xl2tpd
  template: src=xl2tpd.conf.j2 dest=/etc/xl2tpd/xl2tpd.conf
  notify: restart_xl2tpd

- name: Configure CHAP secrets
  lineinfile:
    dest: /etc/ppp/chap-secrets
    regexp: ".*raspi-vpn-server.*"
    line: '* raspi-vpn-server {{ l2tp_vpn_psk }} *'
    create: yes
  notify: restart_xl2tpd

- name: Configure PPP options
  copy: src=options.xl2tpd dest=/etc/ppp/options.xl2tpd
  notify: restart_xl2tpd

- name: Set sysctl configs
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { key: 'net.ipv4.conf.default.rp_filter', value: 0 }
    - { key: 'net.ipv4.conf.default.accept_source_route', value: 0 }
    - { key: 'net.ipv4.conf.all.send_redirects', value: 0 }
    - { key: 'net.ipv4.conf.default.send_redirects', value: 0 }
    - { key: 'net.ipv4.icmp_ignore_bogus_error_responses', value: 1 }



- name: Enable IPSec service
  service: name=ipsec state=started enabled=yes

- name: Enable xl2tpd service
  service: name=xl2tpd state=started enabled=yes
