---
- name: Install mdns dependency
  apt:
    name: '{{ packages }}'
    cache_valid_time: 7200
  vars:
    packages:
    - libavahi-compat-libdnssd-dev
    - libnss-mdns
    - avahi-utils
  register: task_result
  until: task_result is success
  retries: 2
  delay: 5

- name: allow external port
  ufw:
    rule: allow
    port: '{{ externalport }}'
    proto: tcp
    src: '{{ item }}'
  with_items: '{{ allowed_networks }}'

- name: add signalk user
  user:
    name: "{{ signalk_user }}"
    shell: /bin/bash

- name: make config directory
  file:
    path: /opt/signalk/
    state: directory
    mode: 0755
    owner: "{{ signalk_user }}"
    group: "{{ signalk_user }}"

- name: make log directory
  file:
    path: /var/log/signalk
    state: directory
    mode: 0755
    owner: "{{ signalk_user }}"
    group: "{{ signalk_user }}"

- name: copy defaults template
  template:
    src: opt/signalk/defaults.json.j2
    dest: /opt/signalk/defaults.json
    owner: "{{ signalk_user }}"
    group: "{{ signalk_user }}"
    mode: 0644
    force: no

- name: copy service config
  template:
    src: etc/systemd/system/signalk.service.j2
    dest: /etc/systemd/system/signalk.service
    owner: root
    group: root
    force: yes

- name: copy socket config
  template:
    src: etc/systemd/system/signalk.socket.j2
    dest: /etc/systemd/system/signalk.socket
    owner: root
    group: root
    force: yes

- name: copy signalk-update
  copy:
    src: usr/local/bin/signalk-update
    dest: /usr/local/bin/signalk-update
    owner: root
    group: root
    force: no
    mode: 0755

- name: set execute on signalk-server
  file:
    path: /opt/signalk/signalk-server
    state: file
    mode: 0755

- name: install react
  npm:
    name: react
    global: yes
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 5

- name: install signalk --long process--
  npm:
    name: signalk-server
    global: yes
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 5

- name: install signalk plugins
  npm:
    path: /opt/signalk
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 5

- name: install signalk systemd service
  systemd:
    daemon_reload: yes
    name: signalk
    enabled: yes
    state: started
