---
- name: Install necessary packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - busybox-syslogd
  register: task_result
  until: task_result is success
  retries: 2
  delay: 5