# Copyright 2016 Teppo Kurki <teppo.kurki@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
  - name: "Install mdns dependency"
    apt:
      name: {{ packages }}
      state: latest
    vars:
      packages:
      - libavahi-compat-libdnssd-dev state=latest
      - libnss-mdns
      - avahi-utils
      - libavahi-compat-libnssd-dev

  - name: Copy Default SignalK server settings
    copy:
      src: /opt/signalk-server/settings/settings.json
      dest: /etc/signalk-settings.json
      mode: 0644
      owner: "{{ ansible_user }}"
      remote_src: true
    when: signalk_settings_file is not defined
    register: signalk_settings

  - name: Copy Custom SignalK server settings
    copy:
      src: '{{ signalk_settings_file }}'
      dest: /etc/signalk-settings.json
      mode: 0644
      owner: "{{ ansible_user }}"
    when: signalk_settings_file is defined
    register: signalk_settings

  - name: Install SignalK server plugins
    npm:
      name: "{{ item }}"
      path: /opt/signalk-server
      production: yes
    with_items: "{{ signalk_plugins }}"
    when: signalk_plugins is defined

  - name: Restart SignalK server
    service: name=signalk-server state=restarted
    when: signalk_settings.changed
